### ISSUE TITLE
AttributeError: module 'augly' has no attribute 'audio'

### ISSUE THREAD

**Issue by yyjabiding** [facebookresearch/AugLy#159]
## 🐛 Bug

Traceback (most recent call last):
  File "video_aug.py", line 3, in <module>
    import augly.video as vidaugs
  File "/root/anaconda3/envs/zyj/lib/python3.6/site-packages/augly/video/__init__.py", line 4, in <module>
    from augly.video.composition import Compose, OneOf
  File "/root/anaconda3/envs/zyj/lib/python3.6/site-packages/augly/video/composition.py", line 8, in <module>
    from augly.video.helpers import validate_input_and_output_paths
  File "/root/anaconda3/envs/zyj/lib/python3.6/site-packages/augly/video/helpers/__init__.py", line 4, in <module>
    from augly.video.helpers.ffmpeg import (
  File "/root/anaconda3/envs/zyj/lib/python3.6/site-packages/augly/video/helpers/ffmpeg.py", line 10, in <module>
    import augly.audio.utils as audutils
  File "/root/anaconda3/envs/zyj/lib/python3.6/site-packages/augly/audio/__init__.py", line 4, in <module>
    from augly.audio.composition import Compose, OneOf
  File "/root/anaconda3/envs/zyj/lib/python3.6/site-packages/augly/audio/composition.py", line 8, in <module>
    from augly.audio.transforms import BaseTransform
  File "/root/anaconda3/envs/zyj/lib/python3.6/site-packages/augly/audio/transforms.py", line 7, in <module>
    import augly.audio.functional as F
  File "/root/anaconda3/envs/zyj/lib/python3.6/site-packages/augly/audio/functional.py", line 8, in <module>
    import augly.audio.utils as audutils
  File "/root/anaconda3/envs/zyj/lib/python3.6/site-packages/augly/audio/utils.py", line 7, in <module>
    import augly.audio.intensity as audintensity
AttributeError: module 'augly' has no attribute 'audio'

## To Reproduce

1.install augly
2.run sample code import augly.video as vidaugs
3. error occured.

## Environment

 - AugLy Version (0.1.10):
 - OS  centos 7
 - How I installed AugLy 
   pip install augly[av] 
   conda install -c conda-forge python-magic
 - Python version: 3.6

**Comment by zpapakipos** [comment]
Hi @yyjabiding, thanks for reporting this issue! It looks to be the same issue as was reported in https://github.com/facebookresearch/AugLy/issues/137 -- AugLy is currently not compatible with python 3.6, and we need to change the way we import between modules to fix it. I'll prioritize fixing this soon since clearly it's affecting multiple users. In the meantime, I recommend using AugLy with python 3.7 if that's ok for your use case.

**Comment by zpapakipos** [comment]
Update: I landed https://github.com/facebookresearch/AugLy/pull/160 which modified the imports to be python 3.6-compatible. On my side I verified that I have no issue running AugLy in a conda env using python 3.6. Please reopen this issue if anyone sees this issue again!
